# Generated by Django 4.0.6 on 2022-07-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='maestro',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
